# The URL the site will be built for
base_url = "https://bdillo.dev"

# for feeds
title = "bdillo"
description = "bdillo's feed"
generate_feeds = true
feed_filenames = ["atom.xml"]
feed_limit = 20

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
